os: linux
dist: focal
group: dev

jobs:
  include:
#     - language: erlang
#       script:
#       - erl -noshell -eval 'io:fwrite("Hello, World!\n"), init:stop().'
    
#     - language: python
#       python: 
#       - 3.7
#       script: 
#       - python python_hw.py
    
#     - language: python
#       python: 
#       - 3.8
#       script: 
#       - python python_hw.py
    
#     - language: python
#       python:
#       - nightly
#       script: 
#       - python python_hw.py

    - language: perl
      perl: "5.33.0"
      script:
      - perl helloworld.py
      
    - language: perl
      perl: "5.32.0"
      script:
      - perl helloworld.py
    
    - services: 
      - elasticsearch
      script:
      - systemctl status elasticsearch
      - sleep 2400
      - curl 127.0.0.1:9200

before_script:
  - perlbrew install-cpanm --force
      
