os: linux
dist: focal
group: dev

jobs:
  include:
    - language: erlang
      script:
        - erl -noshell -eval 'io:fwrite("Hello, World!\n"), init:stop().'
  include:
    - services: 
        - elasticsearch
      script:
        - systemctl status elasticsearch
        - netstat -nltp
        - sudo ls /var/log/elasticsearch
        - sudo tail /var/log/elasticsearch
   
   
                
