os: linux
dist: focal
group: dev

jobs:
  include:
#     - language: erlang
#       script:
#       - erl -noshell -eval 'io:fwrite("Hello, World!\n"), init:stop().'
    
#     - language: python
#       python: 
#       - 3.7
#       script: 
#       - python python_hw.py
    
#     - language: python
#       python: 
#       - 3.8
#       script: 
#       - python python_hw.py
    
#     - language: python
#       python:
#       - nightly
#       script: 
#       - python python_hw.py
    
    - services: 
      - elasticsearch
      script:
      - systemctl status elasticsearch
      - sudo systemctl stop elasticsearch
      - echo 'test'
#       - sudo echo 'http.port: 9200' >> /etc/elasticsearch/elasticsearch.yml
#       - sudo echo 'network.host: 127.0.0.1' >> /etc/elasticsearch/elasticsearch.yml
      - sudo systemctl start elasticsearch
      - sudo ls /etc/ | grep ela
      - netstat -nltp
      - ifconfig
      - sleep 2412
