os: linux
dist: focal
group: dev

jobs:
  include:
    - language: erlang
      script:
        - erl -noshell -eval 'io:fwrite("Hello, World!\n"), init:stop().'
    
    - language: python
       python:
       - 3.7
       script: 
       - python python_hw.py
    
    - language: python
       python:
       - 3.8
       script: 
       - python python_hw.py
    
    - language: python
       python:
       - nightly
       script: 
       - python python_hw.py
       
  #include:
    #- services: 
     #   - elasticsearch
      #script:
       # - systemctl status elasticsearch
        #- netstat -nltp
        #- sudo ls -altr /var/log/elasticsearch
        #- sudo cat /var/log/elasticsearch/elasticsearch.log
        #- date
        #- sudo cat /etc/elasticsearch/elasticsearch.yml
   
   
                
