
language: perl

jobs:
  include:
   - perl: "5.33.0"
     os: linux
     dist: focal
     group: dev
     script:
     - perl helloworld.pl
   - perl: "5.32.0"
     os: linux
     dist: focal
     group: dev
     script:
     - perl helloworld.pl
